Panda_v2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('mainapp.urls')),
]

mainapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from mainapp import views
from mainapp.views import *

urlpatterns = [
    # url(r'^user/$',views.User_list),
    # url(r'^user/$',UserListView.as_view()),  #关联restful和api
    # url(r'^user/(?P<id>[0-9]+)/$',UserView.as_view()),
    url(r'^$',views.home,name='home'),
    url(r'regist',RegisterView.as_view(),name='regist'),
    url(r'login',LoginView.as_view(),name='login'),
    url(r'vcode',views.vCode,name='vcode'),
    url(r'upload',views.upload),
    url(r'uname/(?P<name>\w+)/$',views.uName),
    url(r'verify/(?P<code>[0-9a-zA-Z]+)/$',views.verifycode),
    url(r'logout',views.logout),
    url(r'addblob',views.addBlob),
    url(r'blob',BlobView.as_view(),name='blob'),
    url(r'show/(?P<blob_id>\d+)$',views.show),
    url(r'replay',views.replay),
    url(r'allreply/(?P<blob_id>\d+)/(?P<num>\d+)$',views.allreply),
]

mainapp/models.py
from django.db import models

# Create your models here.
from tinymce.models import HTMLField


class User(models.Model):
    name = models.CharField(max_length=50,unique=True,verbose_name='用户名')
    passwd = models.CharField(max_length=200,verbose_name='密码')
    phone = models.CharField(max_length=12,verbose_name='电话')
    image = models.ImageField(max_length=200,upload_to='user/images',verbose_name='用户头像')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

class Blob(models.Model):
    blob_type = (
        (0, '美食'),
        (1, '科技'),
        (2, '教育'),
        (3, '娱乐'),
        (4, '财经'),
        (5, '影视'),
        (6, '体育'),
    )

    title = models.CharField(max_length=50,verbose_name='标题')
    btype = models.IntegerField(choices=blob_type,verbose_name='类型')
    summary = models.TextField(default='',verbose_name='概要')
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)  #所属用户
    content = HTMLField(default='',verbose_name='文章内容')
    cnt = models.IntegerField(default=0,verbose_name='点击量')
    publish_time = models.DateTimeField(auto_now=True,verbose_name='发布时间')

    @property
    def type_name(self):
        return self.blob_type[self.btype][1]

#用户评论
class Replay(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,verbose_name='用户')
    blob = models.ForeignKey(Blob,on_delete=models.CASCADE,verbose_name='博客')
    content = HTMLField(default='',verbose_name='评论')
    reply_time = models.DateTimeField(auto_now=True,verbose_name='评论时间')

templates/blob_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑博客</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        strong{
            font-size: 18px;
            font-style: italic;
        }

        #head{
            height: 40px;
            background-color: #bce8f1;
            padding: 5px;
        }
    </style>
</head>
<body>
<div id="head">
    <button id="save" class="btn btn-success"
            style="height: 30px">发布</button>
    <a href="/user"  class="btn btn-success"
            style="height: 30px;position: absolute;right:5px">返回首页</a>
</div>
<form>
    <input type="hidden" name="blob_id" value="{{ blob.id }}">
    <div style="width: 830px;padding: 15px">
    <div class="form-group">
        <strong>标题：</strong><input class="form-control" value="{{ blob.title }}" name="title">
    </div>
    <div>
        {% if blob.btype %}
            <input type="hidden" name="btype" value="{{ blob.btype }}">
            <strong>所属类型：</strong><input class="form-control" value="{{ blob.type_name }}" onfocus="this.blur()">
        {% else %}
        <strong>选择类型：</strong><select class="form-control" name="btype">
                      <option value="0">美食</option>
                      <option value="1">科技</option>
                      <option value="2">教育</option>
                      <option value="3">娱乐</option>
                      <option value="4">财经</option>
                      <option value="5">影视</option>
                      <option value="6">体育</option>
                    </select>
        {% endif %}
    </div>
    <div class="form-group" style="margin-top: 20px">
        <strong>概要：</strong><input class="form-control" name="summary" value="{{ blob.summary }}">
    </div>
    </div>
</form>
<div style="margin: 15px">
    <strong>内容：</strong>
    <textarea name="content">{{ blob.content }}</textarea>
</div>

<div class="modal" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content" style="margin: 0 20px">
  <div class="modal-body">
    <h4><span id="saveMsg">正在操作...</span></h4>
  </div>
</div>
</div>
</div>

<script src="/static/js/blob_edit.js"></script>
</body>
</html>

templates/blob_list.html
{% extends 'home.html' %}
{% block title %}
博客
{% endblock %}
{% block extCss %}
<style>
    .swiperImg > img{
        border-radius: 7px;
    }
</style>
{% endblock %}

{% block content %}
{% if bianji == 1 %}
    <h4 align="center">我的博客</h4>
{% elif zuozhe == 2 %}
    <h4 align="center">{{ user.name }} 的所有文章</h4>
{% else %}
    <h4 align="center">所有博客</h4>
{% endif %}
<table class="table table-hover table-bordered table-striped">
<thead>
<th>序号</th>
<th>类型</th>
<th>标题</th>
{% if not bianji %}
<th>作者</th>
{% endif %}
<th>浏览量</th>
{% if bianji %}
<th style="text-align: center">操作</th>
{% endif %}
</thead>
<tbody>
{% for blob in blobs %}
<tr>
<td>{{ forloop.counter }}</td>
<td>{{ blob.type_name }}</td>
<td><a href="/user/show/{{ blob.id }}">{{ blob.title }}</a></td>
{% if not bianji %}
<td>{{ blob.user.name }}</td>
{% endif %}
<td>{{ blob.cnt }}</td>
{% if bianji %}
<td width="200" style="text-align: center">
<a class="btn-sm btn-primary" href="/user/blob?id={{ blob.id }}">编辑</a>
<a class="btn-sm btn-danger" name="deleteBlob" style="margin-left: 20px;cursor: pointer" title="{{ blob.id }}">删除</a>
</td>
{% endif %}
</tr>
    {% empty %}
    <tr>
    <td colspan="5" align="center">暂无博客</td>
    </tr>
{% endfor %}

</tbody>
</table>


<div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content" style="margin: 0 20px">
  <div class="modal-body">
    <h4><span id="delMsg">确定要删除此篇文章吗?</span></h4>
  </div>
  <div class="modal-footer">
    <button type="button" id="close" class="btn btn-sm btn-default" data-dismiss="modal">关闭</button>
      <button id="ok" type="button" class="btn btn-sm btn-default">确定</button>
  </div>
</div>
</div>
</div>


{% endblock %}

{# 轮播图 #}
{% block right %}
<section class="swiper-container" id="topSwiper">
    <div class="swiper-wrapper">
            <div class="swiper-slide swiperImg" >
                <img src="/static/images/IMG_7307.JPG" width="100%" height="330">
            </div>
            <div class="swiper-slide swiperImg">
                <img src="/static/images/bb.jpg" width="100%" height="330">
            </div>
            <div class="swiper-slide swiperImg">
                <img src="/static/images/IMG_6631.JPG" width="100%" height="330">
            </div>
    </div>
    <!-- 如果需要分页器 -->
    <div class="swiper-pagination"></div>

    <!-- 如果需要导航按钮 -->
{#    <div class="swiper-button-prev"></div>#}
{#    <div class="swiper-button-next"></div>#}

    <!-- 如果需要滚动条 -->
{#    <div class="swiper-scrollbar"></div>#}

{#导航等组件可以放在container之外#}
</section>
{#<div>#}
{#    <img src="/static/images/IMG_7307.JPG" width="100%" height="330">#}
{#</div>#}
{% endblock %}
{% block expscript %}
<script src="/static/js/blob_list.js"></script>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        Panda博客-带给你想要的精彩
    {% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/swiper.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/swiper.min.js"></script>
    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
        }

        #title{
            padding: 15px;
            background-color: white;
            font-size: 16px;
            box-shadow: 2px 2px 0 rgba(235,235,235,0.88);
        }

        #title .col-md-2 a{
            font-size: 16px;
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

        #title a{
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

        .row a:hover{
            color: red;
        }

        .headphoto{
            width: 35px;
            height: 35px;
            border-radius: 50%;
            border: 2px solid #d1d1d1;
        }

        #menu{
            float: left;
            margin: 15px 20px 0 70px ;
        }
        #menu .col-md-2{
            width: 100px;
            float: none;
            padding: 5px;
            margin: 1px 0 1px 0;
            text-align: center;
            font-size: 16px;
        }

        #menu .col-md-2:hover{
            background-color: rgba(49, 176, 213, 0.75);
        }

        #mm{
            background-color: white;
            width: 100px;
            border: 1px solid white;
        }


        #menu a{
            color: #6a6a6a;
            text-decoration: none;
            cursor: pointer;
        }

        #content{
            margin: 15px 20px 0 0;
            float: left;
            width: 60%;
            background-color: white;
{#            border: 1px solid black;#}
{#            height: 500px;#}
            overflow: auto;
        }

        #right{
            margin: 15px 20px 0 0;
            float: left;
            width: 20%;
            background-color: white;
            overflow: auto;
            padding: 2px;
            border-radius: 7px;
            border: 1.5px solid lightgrey;
            box-shadow: 2px 2px 0 rgba(235,235,235,0.88);
        }


    </style>
    {% block extCss %}

    {% endblock %}
</head>
<body style="background-color:rgba(209,209,209,0.24);">
<div id="title">
<div id="row" class="row" style="line-height: 30px;height: 30px">
    {% block header %}
        <div class="col-md-2">
        <strong style="font-size: 24px"><em>Panda博客</em></strong>
        </div>
        <div class="col-md-2">
        <a href="/user">首页<span></span></a>
        </div>
        <div class="col-md-2"><a href="/user/blob">所有博客</a><span></span></div>
        <div class="col-md-2">
            <a href="/user/addblob"><span class="glyphicon glyphicon-pencil"></span>&nbsp;发表博客</a>
            <span></span>
        </div>
        {% if user.name %}
            <div class="col-md-1">
                <a style="text-decoration: none" id="username">{{ user.name }}</a><span></span></div>
            <div class="col-md-1" style="padding-top:-5px;margin: 0">
                <img id="userphoto" src="/static/head/{{ user.image }}" class="headphoto">
            </div>
            <div class="col-md-1">
                <a href="/user/blob?a=1">我的博客</a>
            <span></span>
            </div>
            <div class="col-md-1">
                <a href="/user/logout">退出</a>
            <span></span>
            </div>
        {% else %}
            <div class="col-md-2"><a href="/user/login">登录</a></div>
            <div class="col-md-2">
                <a href="/user/regist">注册</a>
            </div>
        {% endif %}
    {% endblock %}
</div>
</div>
<div id="body">
    <div id="menu">
        {% block menu %}
            <div id="mm">
            <div class="col-md-2" style="margin-top: 5px">
                <a>推 荐</a>
            </div>
            <div class="col-md-2">
                <a>美 食</a>
            </div>
            <div class="col-md-2">
                <a>科 技</a>
            </div>
            <div class="col-md-2">
                <a>教 育</a>
            </div>
            <div class="col-md-2">
                <a>娱 乐</a>
            </div>
            <div class="col-md-2">
                <a>财 经</a>
            </div>
            <div class="col-md-2">
                <a>影 视</a>
            </div>
            <div class="col-md-2" style="margin-bottom: 5px">
                <a>体 育</a>
            </div>
            </div>
        {% endblock %}

    </div>
    <div id="content">
        {% block content %}
            <div style="padding: 5px;">
            <div style="float: left">
            <img src="/static/images/IMG_1875.JPG" width="450" height="310">
            </div>
            <div style="float: left;margin-left: 10px;padding: 5px;">
                <h4  style="font-weight: bolder;padding: 0 0 12px 5px">热门文章</h4>
                {% for user in users %}
                    {% if forloop.counter <= 2 %}
                        {% for blob in user.blob_set.all %}
                        {% if forloop.counter == 1 %}
                            <div style="font-size: 14px;color: gray">
                            <span style="font-size: 16px;font-weight: bolder;color: black">
                                <a href="/user/show/{{ blob.id }}">{{ blob.title }}</a></span>
                            <span style="padding-left: 20px">{{ blob.type_name }}</span><br>
                            <span>{{ blob.publish_time }}</span>
                            <span style="position: absolute;right: 30%">浏览量: {{ blob.cnt }}</span>
                            <hr style="color: lightgrey">
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
            </div>
        {% endblock %}

    </div>
    <div id="right">
        {% block right %}
        <div style="padding: 10px">
        <h4  style="font-weight: bolder;padding: 0 0 12px 5px;">推荐博主</h4>
        {% for user in users %}
            {% if forloop.counter <= 3 %}
                <div style="margin-bottom: 10px">
            <img src="/static/head/{{ user.image }}"
                 style="height: 40px;width: 40px;border-radius: 50%;border: 2px solid #d1d1d1;">
            <span style="padding-left: 20px">
                <a href="/user/blob?user_id={{ user.id }}">{{ user.name }}</a></span>
            </div>
            {% endif %}
        {% endfor %}
        </div>
        {% endblock %}
    </div>
</div>
<div id="foot">
{% block foot %}

{% endblock %}
{% block expscript %}

{% endblock %}
</div>
</body>
</html>

templates/msg.html
{% extends 'home.html' %}
{% block title %}
信息提示页面
{% endblock %}
{% block content %}
<div style="width: 60%;margin:80px auto;">
<h1 style="color: #31b0d5">{{ save_msg }}</h1>
</div>
{% endblock %}
{% block expscript %}
<script>
$.function(
    setTimeout(function () {
        window.open('/user',target='_self')
    },1500)
)
</script>
{% endblock %}

templates/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bootstrap-theme.css">
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.min.js"></script>
    <style>
        #body{
            width: 85%;
            height: 500px;
            margin: 50px auto;
{#            background-color: rgba(211, 211, 211, 0.3);#}
{#            border: 1px solid lightgrey;#}
        }

        #left{
            float: left;
            width: 30%;
            height: 100%;
            background-color: rgba(178, 233, 217, 0.29);
            border: 1px solid gainsboro;
            border-radius: 7px;
            box-shadow: 3px 3px 5px #bbbbbb;
        }

        #right{
            float: left;
            width: 68%;
            height: 100%;
            margin-right: 10px;
            border: 1px solid #b4b8dc;
            border-radius: 7px;
            box-shadow: 2px 2px 2px  #bbbbbb;
        }

        .error{
            display: none;
            color: red;
        }
    </style>
</head>
<body>

<div id="body">
    <div id="right">
        <img src="/static/images/IMG_9675.JPG" width="100%" height="100%"
             style="border-radius: 7px">
    </div>
    <div id="left">
        {% if opt == 1 %}
            <h3 align="center">用 户 注 册</h3>
            <form method="post" action="/user/regist" class="form-horizontal" style="width: 60%;margin: auto">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input class="form-control" id="username" name="username">
                    <span class="error">用户名不能为空</span>
                </div>
                <div class="form-group">
                    <label for="phone">手机号</label>
                    <input class="form-control" id="phone" name="phone">
                    <span class="error">请输入11位手机号</span>
                </div>
                <div class="form-group">
                    <label for="passwd">密码</label>
                    <input class="form-control" type="password" id="passwd" name="passwd">
                    <span class="error">密码不能为空</span>
                </div>
                <div class="form-group">
                    <label>上传头像</label><br>
                    <img class="btn" id="preImg" alt="添加图片" width="80"
                         height="60" style="line-height: 40px;border: 1px dashed gray" onclick="file.click()">
                    <input type="hidden" name="head_path"><span class="error">请上传头像</span>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-success"
                            style="width: 80px" onclick="submitJudge()">注册</button>
                </div>
            </form>
            <div  style="width:68%;margin: auto">

                <div class="form-group">
                    <label>已有账号</label>
                    <a href="/user/login">立即登录</a>
                </div>
            </div>

        <input
               style="display: none"
               onchange="uploadImg(this.files[0])"
               type="file" id="file">
        {% else %}
            <h3 align="center">用 户 登 录</h3>
            <form method="post" action="/user/login" class="form-horizontal" style="width: 60%;margin: auto">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input class="form-control" id="username" name="name" value="{{ name }}">
                    <span class="error">用户名不能为空</span>
                </div>
                <div class="form-group">
                    <label for="passwd">密码</label>
                    <input class="form-control" type="password" id="passwd" name="passwd" value="{{ passwd }}">
                    <span class="error">密码不能为空</span>
                </div>
                <div class="form-group">
                    <label for="vcode">验证码</label>
                    <input class="form-control" id="vcode" name="vcode" placeholder="{{ error_msg }}">
                    <span class="error">验证码不能为空</span>
                </div>
                <div style="width:80%;">
                    <div class="form-group">
                        <img src="/user/vcode" width="120"
                         height="35" id="img">
                        <br/>
                        <a style="cursor: pointer;text-decoration: none;"
                           onclick="flush(img)" class="btn-sm btn-primary">
                            <span class="glyphicon glyphicon-repeat">换一换</span></a>
                    </div>
                </div>
            <div class="form-group" style="margin-top: 35px">
                    <button type="button" class="btn btn-success"
                            style="width: 80px" onclick="submitJudge()">登录</button><br/>
                <span style="color: red;font-size: 14px">{{ dl_msg }}</span>
                </div>
            </form>

            <div style="width:68%;margin: auto">

                <div class="form-group">
                    <label>还没有账号?</label>
                    <a href="/user/regist">立即注册</a>
                </div>
            </div>
        {% endif %}

    </div>

</div>

<script>
    function flush(img) {
        img.src = '/user/vcode?tm='+Math.random();
    }

    function uploadImg(file) {
        console.log(file);
        var xhr = new XMLHttpRequest();
        xhr.open('post','/user/upload',true);
        xhr.onload = function () {
            var data = JSON.parse(xhr.responseText);
            console.log(data.path);
            document.getElementsByName('head_path')[0].value = data.path;
            document.getElementById('preImg').src = '/static/head/'+data.path
        };
        var formdata = new FormData;
        formdata.append('photo',file);
        formdata.append('csrfmiddlewaretoken',
            document.getElementsByName('csrfmiddlewaretoken')[0].value);
        xhr.send(formdata);
    }

{#    function submitJudge(num) {#}
{#        var ipts = document.getElementsByTagName('input');#}
{#        var n = 0;#}
{#        console.log(ipts);#}
{#        for(var i in ipts){#}
{#            var ipt = ipts[i];#}
{#            console.log(ipt);#}
{#            if(ipt.value == ""){#}
{#                ipt.placeholder = "信息不能为空";#}
{#                n ++;#}
{#            }#}
{#        }#}
{#        console.log(n);#}
{#        if(num == '1'){#}
{#            if (n == 1) {#}
{#                document.forms[0].submit();#}
{#            }#}
{#        }else {#}
{#            if (n == 0) {#}
{#                document.forms[0].submit();#}
{#            }#}
{#        }#}
{##}
{#    }#}
</script>
<script src="/static/js/regist.js"></script>
</body>
</html>

templates/replay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>回帖记录</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.min.js"></script>
</head>
<body>
<div>
{% for replay in page.object_list %}
        <div>
        <strong style="color: blue;font-size: 14px">
            {{ replay.user.name }}
        </strong>
        <span style="padding-left: 30px;color: gray;font-size: 12px">{{ replay.reply_time }}</span>
        </div>
        <p style="color: gray">{{ replay.content|safe }}</p>
        <hr style="border: 1px dashed lightgray">
        {% empty %}
        <span style="color: gray">暂无记录</span>
{% endfor %}
</div>
<div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                {# 如果当前页有上一页 #}
                {% if page.has_previous %}
                <a href="/user/allreply/{{ blob_id }}/{{ page.previous_page_number }}"
                   aria-label="Previous">
                {% else %}
                    <a href="#" aria-label="Previous">  {# 没有上一页 #}
                {% endif %}
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {# 页码部分 #}
            {% for num in range %}
                {% if num == page.number %}  {# page.number是当前页对象的页码 #}
                    <li class="active">
                {% else %}
                    <li>
                {% endif %}
                <a href="/user/allreply/{{ blob_id }}/{{ num }}">{{ num }}</a></li>
            {% endfor %}
        
            {# 判断当前页是否有下一页 #}
            <li>
                {% if page.has_next %}
                    <a href="/user/allreply/{{ blob_id }}/{{ page.next_page_number }}"
                       aria-label="Next">
                {% else %}
                    <a href="#" aria-label="Next">
                {% endif %}
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
</body>
</html>

templates/show.html
{% extends 'home.html' %}
{% block content %}
<div style="padding: 10px">
<div>
<h2>{{ blob.title }}</h2>
<span>类型: {{ blob.type_name }}</span><br>
<span>发表时间: {{ blob.publish_time }}</span>
<span style="position: absolute;right: 30%">浏览量: {{ blob.cnt }}</span>
<hr style="color: lightgrey">
</div>
<div>
    <h4 style="font-weight: bolder">概要:{{ blob.summary }}</h4>
    {{ blob.content|safe }}
</div>
<hr style="color: lightgrey">
<div>
    <div style="width: 100%;height:38px;
    background-color:rgba(99,222,135,0.62);padding: 5px">
        <span style="font-weight: bolder;font-size: 18px">回帖</span>
        <button style="position: absolute;right: 27%;height: 28px;"
                id="save" class="btn-sm btn-primary">提交</button>
    </div>
    <form>
        <input type="hidden" name="blob_id" value="{{ blob.id }}">
        <textarea name="content"></textarea>
    </form>
</div>
</div>

{% endblock %}


{% block right %}
<div style="padding: 10px;">
<div>
    <h4  style="font-weight: bolder;padding: 0 0 12px 5px;">
        <span class="glyphicon glyphicon-user"></span> 作者信息</h4>
    <img src="/static/head/{{ blob.user.image }}"
         style="height: 50px;width: 50px;border-radius: 50%;border: 2px solid #d1d1d1;">
    <span style="padding-left: 10px">{{ blob.user.name }}</span>
    <span style="padding-left: 10px">发帖数: {{ blob.user.blob_set.all.count }}</span>
</div>
<hr>
<div>
    <p  style="font-weight: bolder;padding-bottom: 12px;font-size: 16px">回帖记录</p>
</div>
<div style="height: auto">
<iframe src="/user/allreply/{{ blob.id }}/1"
        frameborder="0" width="100%" scrolling="no" id="frame"
        onload="changeHeight()"></iframe>

</div>
</div>

{# 模态框 #}
<div class="modal" id="replayModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content" style="margin: 0 20px">
  <div class="modal-body">
    <h4><span id="replayMsg"></span></h4>
  </div>
  <div class="modal-footer">
    <button type="button" id="close" class="btn btn-sm btn-default" data-dismiss="modal">关闭</button>
      <button id="ok"  type="button" class="btn btn-sm btn-default">登录</button>
  </div>
</div>
</div>
</div>


{% endblock %}

{% block expscript %}
<script src="/static/js/show.js"></script>
{% endblock %}